services:
  serve:
    extends: base
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST:?err}
      - VIRTUAL_PORT=${HTTP_PORT:?err}
      - HTTP_PORT=${HTTP_PORT:?err}
    expose:
      - "$HTTP_PORT"
    networks:
      - proxy
    profiles:
      - default

  test:
    extends: base
    command:
      - test
      - "login::"
    environment:
      - HTTP_PORT=0
    env_file:
      - ./.env.test
    profiles:
      - test

  base:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL:?err}
      - EMAIL_CLIENT_AUTHORIZATION_TOKEN=${EMAIL_CLIENT_AUTHORIZATION_TOKEN:?err}
      - EMAIL_CLIENT_BASE_URL=${EMAIL_CLIENT_BASE_URL:?err}
      - EMAIL_CLIENT_SENDER_EMAIL=${EMAIL_CLIENT_SENDER_EMAIL:?err}
      - HMAC_SECRET=${HMAC_SECRET:?err}
      - REDIS_URI=${REDIS_URI:?err}
      - RUST_LOG=${RUST_LOG:-info}
      - TEST_LOG=${TEST_LOG:-false}
    networks:
      - default
      - postgres
    volumes:
      - ../../:/home/app/app
      - cargo:/home/app/.cargo

  redis6:
    image: redis:6-alpine
    ports:
      - 6379:6379

volumes:
  cargo:

networks:
  proxy:
    name: services_default
  postgres:
    name: services_default
