services:
  serve:
    extends: base
    env_file:
      - ./.env.serve
    networks:
      - proxy
    profiles:
      - default

  test:
    extends: base
    command:
      - test
    env_file:
      - ./.env.test
    profiles:
      - test

  base:
    build: .
    networks:
      - default
      - postgres
    profiles:
      - dummy
    volumes:
      - ../../:/home/app/app
      - cargo:/home/app/.cargo

  redis6:
    image: redis:6-alpine

volumes:
  cargo:

networks:
  proxy:
    name: services_default
  postgres:
    name: services_default
