---
kind: pipeline
name: default

steps:
- name: build
  image: quay.io/testcontainers/dind-drone-plugin
  environment:
    CI_WORKSPACE: "/drone/src"
  volumes:
  - name: dockersock
    path: /var/run
  commands:
    - sleep 5 # to allow docker to start
    - docker build .

services:
- name: docker
  image: docker:dind
  priviledged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
