[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-http = "3.0.4"
actix-web = "4.0.1"
serde = "1.0.136"
tokio = "1.17.0"
dotenv = "0.15.0"
chrono = "0.4.19"
tracing = { version = "0.1.32", features = ["log"] }
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.9", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3.2"
tracing-log = "0.1.2"

[dependencies.uuid]
version = "1.0.0-alpha.1"
features = ["v4"]

[dependencies.sqlx]
version = "0.5.11"
default-features = false
features = [
  "runtime-actix-rustls",
  "macros",
  "postgres",
  "uuid",
  "chrono",
  "migrate"
]

[dev-dependencies]
once_cell = "1.10.0"
reqwest = "0.11.10"
