[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-http = "=3.0.0-beta.12"
actix-web = "=4.0.0-beta.11"
serde = "1.0.130"
tokio = "1.14.0"
dotenv = "0.15.0"
chrono = "0.4.19"
tracing = { version = "0.1.29", features = ["log"] }
tracing-futures = "0.2.5"
tracing-subscriber = { version = "^0.2.12", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "^0.2.2"
tracing-log = "^0.1.2"

[dependencies.uuid]
version = "0.8.2"
features = ["v4"]

[dependencies.sqlx]
version = "0.5.7"
default-features = false
features = [
  "runtime-actix-rustls",
  "macros",
  "postgres",
  "uuid",
  "chrono",
  "migrate"
]

[dev-dependencies]
once_cell = "1.8.0"
reqwest = "0.11.6"
