services:
  zero2prod:
    image: ssipos/zero2prod:latest
    container_name: zero2prod
    networks:
      - postgres
      - proxy

  redis6:
    image: redis:6-alpine

networks:
  proxy:
    name: services_default
  postgres:
    name: services_default
