services:
  zero2prod:
    build: .
    container_name: zero2prod
    env_file:
      - .env.production
    networks:
      - postgres
      - proxy

networks:
  proxy:
    name: services_default
  postgres:
    name: services_default
