POST https://mandrillapp.com/api/1.0/messages/send
Content-Type: application/json

{
  "key": "{{EMAIL_CLIENT_AUTHORIZATION_TOKEN}}",
  "message": {
    "to": [
      {
        "email": "null@ssipos.ro",
        "name": "Sebastian Sipos"
      }
    ],
    "from_email": "zero2prod@ssipos.ro",
    "from_name": "Zero2Prod - Ssipos",
    "subject": "Hello, World!",
    "text": "Hello from Mailchimp",
    "html": "<p>Hello from Mailchimp!</p>"
  }
}
