POST {{EMAIL_CLIENT_BASE_URL}}/email
api-key:"{{EMAIL_CLIENT_AUTHORIZATION_TOKEN}}"

{
    "to": [
      {
        "email": "sebastiansipos90@gmail.com",
        "name": "Sebastian Sipos"
      }
    ],
    "sender": {
        "email": "zero2prod@ssipos.ro",
        "name": "Zero2Prod - Ssipos"
    },
    "subject": "Hello, World!",
    "textContent": "Hello from zero2prod",
    "htmlContent": "<p>Hello from zero2prod!</p>"
}
